### ISSUE TITLE
RC2 generates unexpected velocity.log

### ISSUE THREAD

**Issue by diwakergupta** [google/auto#151]
Since upgrading to 1.0rc2, whenever I run `mvn compile`, I end up with an unexpected `velocity.log` file in the directory. This will surprise users, breaks `.gitignore` in projects and unnecessarily pollutes the workspace. Here are the contents of my log file::

```
2014-10-27 12:51:19,367 - Log4JLogChute initialized using file 'velocity.log'
2014-10-27 12:51:19,368 - Initializing Velocity, Calling init()...
2014-10-27 12:51:19,368 - Starting Apache Velocity v1.7 (compiled: 2010-11-19 12:14:37)
2014-10-27 12:51:19,368 - Default Properties File: org/apache/velocity/runtime/defaults/velocity.properties
2014-10-27 12:51:19,368 - Trying to use logger class org.apache.velocity.runtime.log.AvalonLogChute
2014-10-27 12:51:19,368 - Target log system for org.apache.velocity.runtime.log.AvalonLogChute is not available (java.lang.NoClassDefFoundError: org/apache/log/format/Formatter).  Falling back to next log system...
2014-10-27 12:51:19,368 - Trying to use logger class org.apache.velocity.runtime.log.Log4JLogChute
2014-10-27 12:51:19,368 - Using logger class org.apache.velocity.runtime.log.Log4JLogChute
2014-10-27 12:51:19,371 - ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.FileResourceLoader
2014-10-27 12:51:19,372 - Do unicode file recognition:  false
2014-10-27 12:51:19,372 - FileResourceLoader : adding path '.'
2014-10-27 12:51:19,382 - ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.
2014-10-27 12:51:19,383 - Loaded System Directive: org.apache.velocity.runtime.directive.Stop
2014-10-27 12:51:19,384 - Loaded System Directive: org.apache.velocity.runtime.directive.Define
2014-10-27 12:51:19,384 - Loaded System Directive: org.apache.velocity.runtime.directive.Break
2014-10-27 12:51:19,385 - Loaded System Directive: org.apache.velocity.runtime.directive.Evaluate
2014-10-27 12:51:19,385 - Loaded System Directive: org.apache.velocity.runtime.directive.Literal
2014-10-27 12:51:19,386 - Loaded System Directive: org.apache.velocity.runtime.directive.Macro
2014-10-27 12:51:19,387 - Loaded System Directive: org.apache.velocity.runtime.directive.Parse
2014-10-27 12:51:19,389 - Loaded System Directive: org.apache.velocity.runtime.directive.Include
2014-10-27 12:51:19,390 - Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
2014-10-27 12:51:19,414 - Created '20' parsers.
2014-10-27 12:51:19,418 - Velocimacro : "velocimacro.library" is not set.  Trying default library: VM_global_library.vm
2014-10-27 12:51:19,418 - Velocimacro : Default library not found.
2014-10-27 12:51:19,418 - Velocimacro : allowInline = true : VMs can be defined inline in templates
2014-10-27 12:51:19,418 - Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
2014-10-27 12:51:19,418 - Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
2014-10-27 12:51:19,418 - Velocimacro : autoload off : VM system will not automatically reload global library macros
2014-10-27 12:51:19,458 - Velocimacro : added VM equalsThatExpression: source=autovalue.vm
2014-10-27 12:51:19,458 - Velocimacro : added VM hashCodeExpression: source=autovalue.vm
```
