### ISSUE TITLE
AutoValue cannot handle the same method from multiple interfaces.

### ISSUE THREAD

**Issue by JakeWharton** [google/auto#267]
```java
  public void testTwoInterfacesOneMethod() {
    JavaFileObject interface1 = JavaFileObjects.forSourceLines(
        "foo.bar.Interface1",
        "package foo.bar;",
        "",
        "public interface Interface1 {",
        "  int something();",
        "}");
    JavaFileObject interface2 = JavaFileObjects.forSourceLines(
        "foo.bar.Interface2",
        "package foo.bar;",
        "",
        "public interface Interface2 {",
        "  int something();",
        "}");
    JavaFileObject javaFileObject = JavaFileObjects.forSourceLines(
        "foo.bar.Thing",
        "package foo.bar;",
        "",
        "import com.google.auto.value.AutoValue;",
        "",
        "@AutoValue",
        "public abstract class Thing implements Interface1, Interface2 {",
        "  public static Thing create(int something) {",
        "    return new AutoValue_Thing(something);",
        "  }",
        "}");
    JavaFileObject expectedOutput = JavaFileObjects.forSourceLines(
        "foo.bar.AutoValue_Thing",
        "package foo.bar;",
        "",
        "import javax.annotation.Generated;",
        "",
        "@Generated(\"" + AutoValueProcessor.class.getName() + "\")",
        "final class AutoValue_Thing extends Thing {",
        "  private final int something;",
        "",
        "  AutoValue_Thing(int something) {",
        "    this.something = something;",
        "  }",
        "",
        "  @Override public int something() {",
        "    return something;",
        "  }",
        "",
        "  @Override public String toString() {",
        "    return \"Thing{\"",
        "        + \"something=\" + something",
        "        + \"}\";",
        "  }",
        "",
        "  @Override public boolean equals(Object o) {",
        "    if (o == this) {",
        "      return true;",
        "    }",
        "    if (o instanceof Thing) {",
        "      Thing that = (Thing) o;",
        "      return (this.something == that.something());",
        "    }",
        "    return false;",
        "  }",
        "",
        "  @Override public int hashCode() {",
        "    int h = 1;",
        "    h *= 1000003;",
        "    h ^= this.something;",
        "    return h;",
        "  }",
        "}"
    );
    assertAbout(javaSources())
        .that(ImmutableList.of(interface1, interface2, javaFileObject))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and().generatesSources(expectedOutput);
  }
```
```
foo/bar/Thing.java:6: error: @AutoValue processor threw an exception: java.lang.IllegalArgumentException: Multiple entries with same value: something()=something and something()=something
public abstract class Thing implements Interface1, Interface2 {
                ^
  	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
  	at com.google.common.collect.RegularImmutableBiMap.<init>(RegularImmutableBiMap.java:131)
  	at com.google.common.collect.ImmutableBiMap.copyOf(ImmutableBiMap.java:210)
  	at com.google.auto.value.processor.AutoValueProcessor.methodToPropertyNameMap(AutoValueProcessor.java:535)
  	at com.google.auto.value.processor.AutoValueProcessor.defineVarsForType(AutoValueProcessor.java:498)
  	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:410)
  	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:152)
```

**Comment by JakeWharton** [comment]
This worked in either 1.0 or 1.1. I'm not sure when the regression came as we we're on a ~~forever~~ fork to add things like Parcelable support.

**Comment by eamonnmcmanus** [comment]
I'm pretty sure I know exactly when the change happened. I will look into fixing it. Thanks for the regression test!
(https://github.com/google/auto/commit/9d4ce9ec8f73a0f7fb59a265e6035b0af6ae8389)

**Comment by eamonnmcmanus** [comment]
As a workaround, you can override the multiply-inherited method in the `@AutoValue` class. In the example:
```java
@AutoValue
public abstract class Thing implements Interface1, Interface2 {
  @Override public abstract int something();
  public static Thing create(int something) {
    return new AutoValue_Thing(something);
  }
}
```

**Comment by JakeWharton** [comment]
Oh, cool. Will do that for now. Thanks.

**Comment by eamonnmcmanus** [comment]
This should be fixed now.

**Comment by leventov** [comment]
Seems like this is a bug of  `MoreElements.getLocalAndInheritedMethods()`, isn't it?

**Comment by eamonnmcmanus** [comment]
The bug was there, yes.

**Comment by leventov** [comment]
Are there plans to fix it in `auto-common`?

**Comment by eamonnmcmanus** [comment]
I'm not sure I understand. The bug should be fixed in auto-common. Do you have reason to think that it isn't?

**Comment by leventov** [comment]
As far as I understand It is fixed in auto-value (by extra filtering of methods returned from `getLocalAndInheritedMethods()`), but not auto-common, because `getLocalAndInheritedMethods()` itself still returns dup methods

**Comment by eamonnmcmanus** [comment]
Hmm, I was wrong to say that the bug was in `getLocalAndInheritedMethods()`. That method is doing what it's specified to do. It's not clear to me that we should change it to cover the case where a method with the same signature is inherited along multiple paths. Not only would that change a behaviour that callers may be depending on, it would mean some nontrivial logic to handle methods with generic parameters, as well as a potentially arbitrary choice as to which of the duplicates to remove.

We could reasonably mention this point in the documentation of that method, though.

**Comment by leventov** [comment]
Good points, thanks.
