### ISSUE TITLE
Cannot compile with JDK 9-ea+151 and AutoValue 1.4-rc2

### ISSUE THREAD

**Issue by andrewgaul** [google/auto#426]
Using JDK 9-ea+151 and AutoValue 1.4-rc2 I cannot compile Apache jclouds:

```
$ mvn clean test-compile -e
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project jclouds-core: Compilation failure: Compilation failure:
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[234,21] cannot find symbol
[ERROR] symbol:   class AutoValue_JsonTest_SerializedNamesType
[ERROR] location: class org.jclouds.json.JsonTest.SerializedNamesType
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[289,72] package AutoValue_JsonTest_SerializedNamesNestedWithBuilder does not exist
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[312,66] package AutoValue_JsonTest_SerializedNamesWithBuilder does not exist
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[337,21] cannot find symbol
[ERROR] symbol:   class AutoValue_JsonTest_SerializedNamesTooFewType
[ERROR] location: class org.jclouds.json.JsonTest.SerializedNamesTooFewType
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[362,21] cannot find symbol
[ERROR] symbol:   class AutoValue_JsonTest_NestedSerializedNamesType
[ERROR] location: class org.jclouds.json.JsonTest.NestedSerializedNamesType
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project jclouds-core: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:538)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:152)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jclouds-core
```

This issue relates to #401 but has a different symptom.  JDK 9-ea+142 vs. 9-ea+151 appears to cause this regression.  Note that you will need to use a custom branch to avoid other pitfalls as this comment discusses: https://github.com/google/auto/issues/401#issuecomment-257178091

**Comment by eamonnmcmanus** [comment]
Are there any other diagnostics? I'm wondering if some preceding message might explain why it can't find AutoValue_JsonTest_SerializedNamesType etc. Also, this doesn't seem to be related to #401 apart from the fact that it's about compiling the same code on the same platform.

**Comment by andrewgaul** [comment]
Here is a complete log:

https://gist.github.com/andrewgaul/889eedc5b29be54275ba661c8ed9d553

**Comment by eamonnmcmanus** [comment]
Are you sure that this is being compiled with the AutoValue processor in the classpath? Those errors look like what would happen if it were not.

**Comment by andrewgaul** [comment]
I am sorry, this issue only occurs with JDK 9-ea151; build 152 resolves it.

**Comment by eamonnmcmanus** [comment]
OK, thanks for keeping track of Java 9 compliance all the same! We wouldn't have known about the problem in #401 without you.
